<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicoRepository extends EntityRepository
{
}
