<?php

namespace AppBundle\Repository;

/**
 * AspiranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AspiranteRepository extends \Doctrine\ORM\EntityRepository
{
}
