<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoRepository extends EntityRepository
{
    public function findAllOrderByCurso()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT c FROM AppBundle:Curso c ORDER BY c.curso ASC"
            )
            ->getResult();
    }
}
