<?php

namespace AppBundle\Repository;

/**
 * EstatusExamenGeneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstatusExamenGeneralRepository extends \Doctrine\ORM\EntityRepository
{
}
