<?php

namespace AppBundle\Repository;

/**
 * ExamenGeneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenGeneralRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrderByExamenGeneral($semestre)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e FROM AppBundle:ExamenGeneral e
                  JOIN e.semestre s
                  WHERE s.semestre = :semestre
                  ORDER BY e.nombre ASC"
            )
            ->setParameter('semestre', $semestre)
            ->getResult();
    }
}
