<?php

namespace AppBundle\Repository;

/**
 * ProgramaMaestriaExternoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaMaestriaExternoRepository extends \Doctrine\ORM\EntityRepository
{
}
