<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaRepository extends EntityRepository
{
    public function findAllBySemestreInscrito($slug, $semestre_actual)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM AppBundle:Programa p
                    JOIN p.alumno a
                    JOIN p.semestres s
                    WHERE a.slug = :slug
                    AND s.semestre = :semestre_actual"
            )
            ->setParameter('slug', $slug)
            ->setParameter('semestre_actual', $semestre_actual)
            ->getResult();
    }
}
