<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SemestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemestreRepository extends EntityRepository
{
    public function findAllSemestre()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s FROM AppBundle:semestre s
                  ORDER BY s.semestre ASC
                    "
            )

            ->getResult();
    }
}
