<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SemestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemestreRepository extends EntityRepository
{

    public function findAllBySemestre($semestre, $programa)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a FROM AppBundle:Alumno a
                    JOIN a.programas p
                    JOIN p.semestres s
                    WHERE s.semestre = :semestre
                    AND p.programa = :programa
                    ORDER BY a.paterno ASC"
            )
            ->setParameter('semestre', $semestre)
            ->setParameter('programa', $programa)
            ->getResult();
    }
}
