# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
#
#    alumno.directory_namer:
#            class: 'AppBundle\Service\DirectoryNamer'
#            arguments: ['%kernel.root_dir%']
#
#    namer.media_file:
#        class: 'AppBundle\Namer\Namer'
#        tags:
#            - { name: namer }